### ISSUE TITLE
Mina 1.0.2+ error "bash: bundle: command not found" when using `mina console`

### ISSUE THREAD

**Issue by HappyEmu** [mina-deploy/mina#476]
Hi

I am using Mina version 1.0.3 in a Rails project. When I try to connect to the production console using `mina console` I get the following error: `bash: bundle: command not found`. I'm using rbenv on the server where the app is deployed, the `:environment` task looks as follows:

```ruby
task :environment do
  invoke :'rbenv:load'
end
```

While `mina ssh`, `mina log` and `mina deploy` work flawlessly, `mina console`, `mina rake` and the likes all produce the above mentioned error.

Am I doing something wrong or is this a bug?

**Comment by d4be4st** [comment]
I managed to reproduce it.

Have a logical error in my code. Will try to fix it.

**Comment by molfar** [comment]
@d4be4st so how to deal with this error?

**Comment by Xenofex** [comment]
Encountered the same error here. `mina console` used to depend on the `environment` task back in 0.3.8, but not anymore in 1.0.3. It definitely should depend on the 'environment' task.

**Comment by Xenofex** [comment]
Created #492 to address this

**Comment by molfar** [comment]
Is it ok that environment would be invoked twice, in Mina::DSL.run and in run_commands task?

**Comment by d4be4st** [comment]
You are correct @molfar 

Need to add some specs to this but #aaf50c5 should fix this

**Comment by bobmaerten** [comment]
That does not seems to fix (for me at least). I use rbenv and my gems shims are not anywhere in my `$PATH`, so I have to force it in `:environment` task

```ruby
task :environment do
  invoke 'rbenv:load'
  command %[ export PATH="$PATH:$HOME/.rbenv/shims" ]
end
```

if I override [default console task](https://github.com/mina-deploy/mina/blob/v1.0.6/tasks/mina/rails.rb#L15) by prepending environment load, my rails console task works:
```ruby
task console: :environment do
  set :execution_mode, :exec
  in_path fetch(:current_path).to_s do
    command %{#{fetch(:rails)} console}
  end
end
```

**Comment by molfar** [comment]
Mina 1.0.6 with rbenv still not working...
bash: bundle: command not found
It lloks like bug is not really fixed yet

**Comment by Xenofex** [comment]
This is still there.

```ruby
task :run_commands do
  if commands.run_default?
    invoke :environment
    commands.run(:remote)
  end
end
```

It appears that `commands.run(:remote)` happens before `invoke :environment`. I'm still figuring out why.

**Comment by Xenofex** [comment]
Happy New Year!

And... any updates on this?

**Comment by xikaos** [comment]
@Xenofex I hope so. https://github.com/mina-deploy/mina/commit/aaf50c597223f089103cb9b0d872bd4435edefed

**Comment by stereodenis** [comment]
@xikaos 1.0.6 not work's for me

**Comment by havran** [comment]
Hi. I have same problem on my vagrant Ubuntu machine ().

```
vagrant@vagrant-ubuntu-uidis:/data/form-builder-rails-mina$ mina -V
Mina, version v1.0.6
```

```
vagrant@vagrant-ubuntu-uidis:/data/form-builder-rails-mina$ mina console
vagrant@localhost's password:
bundler: command not found: rails
Install missing gem executables with `bundle install`
-----> Loading rbenv
Connection to localhost closed.
```

**Comment by ajahongir** [comment]
having same issue

**Comment by HappyEmu** [comment]
@d4be4st Could we reopen this issue? Seems like the bug still persists.

**Comment by bindiry** [comment]
I having same issue.
mina 1.0.6 with rbenv

**Comment by bobmaerten** [comment]
I gave up on `mina console`-ing, I just ssh to my server and `bundle exec rails console` now. :-/

**Comment by Martin288** [comment]
Having same issue.

mina 1.0.6 with rvm.

Currently I just add the below codes and it seems it successfully inject the dependence `:enviroment` and avoid launching the console twice mentioned by @bobmaerten.


```ruby
# Fix https://github.com/mina-deploy/mina/issues/476
task :console => :environment do
end
```

**Comment by shvetsov** [comment]
@Martin288 or just
`task console: :environment`

**Comment by molfar** [comment]
I think everything should work out of the box, without any manipulations

**Comment by Martin288** [comment]
@shvetsov right, you can omit the empty block.
@molfar so do I.

**Comment by leyafo** [comment]
just add `command %{export PATH="$PATH:$HOME/.rbenv/shims"}` before execute `bundle exec` command.
Mina setup like shit!

**Comment by 0x01f7** [comment]
Create #551 to fix this.
